name = "blog"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BLOG_TITLE = "My Blog"
POSTS_PER_PAGE = "10"

# Create KV namespace: npx wrangler kv namespace create BLOG_KV
# Then fill in the id below
[[kv_namespaces]]
binding = "BLOG_KV"
id = "bb2239bb83224db1a75e5fb4e52c66aa"


# Set secrets via: npx wrangler secret put ADMIN_USER
#                  npx wrangler secret put ADMIN_PASS
